### ISSUE TITLE
Progress beta state...

### ISSUE THREAD

**Issue by flyingrub** [flyingrub/scdl#2]
## Working
- [x] Automatically detect which kind of Soundcloud's link you have provided
- [x] Download all song of an user
- [x] Download all song & repost of an user
- [x] Download all song of one playlist
- [x] Download all song of all playlist of an user
- [x] Download all song of an user's favorites
- [x] Set the tags with mutagen (title / Arstist name / album = 'Soundcloud' / Artwork)
- [x] Custom Offset
- [x] Add the artist name to the filename if it isn't in the filename already
## Todo
- [ ] rtmp support
## Solved from the bash version
- Actually open Issues here that are fixd in the python version
- https://github.com/lukapusic/soundcloud-dl/issues/85
- https://github.com/lukapusic/soundcloud-dl/issues/101
- https://github.com/lukapusic/soundcloud-dl/issues/82
- https://github.com/lukapusic/soundcloud-dl/issues/81
- https://github.com/lukapusic/soundcloud-dl/issues/77
